name       : python-sphinx-rtd-theme
version    : 1.0.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/s/sphinx_rtd_theme/sphinx_rtd_theme-1.0.0.tar.gz : eec6d497e4c2195fa0e8b2016b337532b8a699a68bcb22a512870e16925c6a5c
homepage   : https://github.com/readthedocs/sphinx_rtd_theme
license    : MIT
component  : programming.python
summary    : Read the Docs theme for Sphinx
description: |
    This Sphinx theme was designed to provide a great reader experience for documentation users on both desktop and mobile devices. This theme is commonly used with projects on Read the Docs but can work with any Sphinx project.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-sphinx
build      : |
    %python3_setup
install    : |
    %python3_install
