name       : python-sphinx-rtd-theme
version    : 1.1.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/s/sphinx_rtd_theme/sphinx_rtd_theme-1.1.1.tar.gz : 6146c845f1e1947b3c3dd4432c28998a1693ccc742b4f9ad7c63129f0757c103
homepage   : https://github.com/readthedocs/sphinx_rtd_theme
license    : MIT
component  : programming.python
summary    : Read the Docs theme for Sphinx
description: |
    This Sphinx theme was designed to provide a great reader experience for documentation users on both desktop and mobile devices. This theme is commonly used with projects on Read the Docs but can work with any Sphinx project.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-docutils
    - python-sphinx
setup      : |
    %patch -p1 < $pkgfiles/0001-Make-theme-work-with-docutils-0.18+.patch
build      : |
    %python3_setup
install    : |
    %python3_install
