name       : python-sphinx-rtd-theme
version    : 0.2.5_1
release    : 3
source     :
    - https://pypi.python.org/packages/59/e4/9e3a74a3271e6734911d3f549e8439db53b8ac29adf10c8f698e6c86246b/sphinx_rtd_theme-0.2.5b1.tar.gz : d99513e7f2f8b9da8fdc189ad83df926b83d7fb15ad7ed07f24665d1f29d38da
license    : MIT
component  : programming.python
summary    : Read the Docs theme for Sphinx
description: |
    Read the Docs theme for Sphinx
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-sphinx
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
